// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

type Token struct {
	ID        string
	ExpiresAt string
}

type User struct {
	ID             string
	HashedPassword string
	Email          string
}
